#DEFAULT
server:
  port: 8081
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    #static-path-pattern: /resources/**
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
#  profiles:
#    active: local
#    active: '@active.profile@'
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: r2dbc:mysql://127.0.0.1:1318/webflux?serverTimezone=Asia/Seoul
    username: root
    password: 1318
# log 설정
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
config:
  upload-file-path: /home/standard/upload/

#---
##DEV
#spring:
#  profiles: dev
#  
#---
##PROD
#spring:
#  profiles: prod